# Generated by Django 4.2.1 on 2023-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
