# Generated by Django 4.2.1 on 2023-06-25 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venta_estado_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='imagen1',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 20, 17, 58, 158488)),
        ),
    ]
