# Generated by Django 4.2.1 on 2023-06-25 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_detalleventa_imagen1_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 20, 31, 3, 334026)),
        ),
    ]
