# Generated by Django 4.2.1 on 2023-06-25 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_venta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='imagen1',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 1, 43, 41, 846928, tzinfo=datetime.timezone.utc)),
        ),
    ]
