# Generated by Django 4.2.1 on 2023-07-06 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_detalleventa_imagen1_detalleventa_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='imagen',
            field=models.CharField(default='https://i.kym-cdn.com/entries/icons/facebook/000/038/239/maxresdefault.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 0, 37, 592588, tzinfo=datetime.timezone.utc)),
        ),
    ]
