# Generated by Django 4.2.1 on 2023-07-06 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_detalleventa_imagen_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 35, 37, 843101, tzinfo=datetime.timezone.utc)),
        ),
    ]
